name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:odin-unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libchamplain-0.12-dev libchamplain-gtk-0.12-dev libclutter-1.0-dev libclutter-gtk-1.0-dev libecal2.0-dev libedataserver1.2-dev libgeoclue-2-dev libgeocode-glib-dev libgranite-dev libgtk-3-dev libhandy-1-dev libgdata-dev libical-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  flatpak:
    name: Flatpak
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:daily
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
        with:
          bundle: tasks.flatpak
          manifest-path: io.elementary.tasks.yml
          run-tests: true
          repository-name: appcenter
          repository-url: https://flatpak.elementary.io/repo.flatpakrepo
          cache-key: "flatpak-builder-${{ github.sha }}"

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: elementary/actions/vala-lint@master
