name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:odin-unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libchamplain-0.12-dev libchamplain-gtk-0.12-dev libclutter-1.0-dev libclutter-gtk-1.0-dev libecal2.0-dev libedataserver1.2-dev libgeoclue-2-dev libgeocode-glib-dev libgranite-dev libgtk-3-dev libhandy-1-dev libgdata-dev libical-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  flatpak:
    runs-on: ubuntu-latest

    container:
      image: docker.io/bilelmoussaoui/flatpak-github-actions
      options: --privileged

    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions@v2
      with:
        bundle: "io.elementary.tasks.flatpak"
        manifest-path: "io.elementary.tasks.yml"

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/vala-lint@master
