name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: elementary/docker:odin-unstable

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y libecal2.0-dev libedataserver1.2-dev libgranite-dev libgtk-3-dev libhandy-1-dev libical-dev meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: elementary/actions/vala-lint@master
